services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - nextcloud-data:/var/www/html/data
      - ./data/nextcloud/config:/var/www/html/config
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${HOSTNAME},localhost,192.168.0.110
      - NEXTCLOUD_ADMIN_USER=Irfan
      - NEXTCLOUD_ADMIN_PASSWORD=ComputerEngineering
      - TZ=Europe/Skopje

  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ./data/samba-share:/mount
    environment:
      - USERID=1000
      - GROUPID=1000
      - TZ=Europe/Skopje
    command: >
      -p
      -s "CloudShare;/mount;yes;no;no;all;none"
      -u "irfan;ComputerEngineering"
    healthcheck:
      disable: true

  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./data/jupyter:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - TZ=Europe/Skopje
    healthcheck:
      disable: true

  llama:
    image: samueltallet/alpine-llama-cpp-server:latest
    container_name: llama
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /home/irfan/mini-cloud/models/llama-3-1b:/models:ro
    environment:
      - LLAMA_ARG_MODEL=/models/model.gguf
      - LLAMA_ARG_PORT=8000
      - LLAMA_ARG_ALIAS=llama-3-1b
      - TZ=Europe/Skopje

  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./website:/usr/share/nginx/html:ro
    environment:
      - TZ=Europe/Skopje

  chat:
    image: nginx:alpine
    container_name: chat
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./chat-ui:/usr/share/nginx/html:ro
      - ./chat-ui/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=Europe/Skopje
      
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8086:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - cadvisor
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus   
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472"
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=PMPV
      - TZ=Europe/Skopje
    volumes:
      - grafana-data:/var/lib/grafana
      
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    pid: "host"
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev)($|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro  
      
  chat-ui:
    build: ./llm-chat-ui-docker
    image: irfanuruchi/llm-chat-ui:latest
    container_name: llm-chat-ui
    restart: unless-stopped
    ports:
      - "3001:8080"
    environment:
      - TZ=Europe/Skopje


volumes:
  nextcloud-data:
  prometheus-data:
  grafana-data:

# no version: line needed for Compose v2
